# === Datasource ===
quarkus.datasource.db-kind=postgresql

# Dev-Profil: lokale Entwicklung (Quarkus direkt + Docker nur fuer DB)
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/prse
%dev.quarkus.datasource.username=prse
%dev.quarkus.datasource.password=prse

# Prod-Profil: Docker Compose (Backend im Container)
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/prse
%prod.quarkus.datasource.username=prse
%prod.quarkus.datasource.password=prse

# === Hibernate ORM ===
quarkus.hibernate-orm.database.generation=drop-and-create
